import z from 'zod';
import { BitbucketClient } from '../clients/bitbucket-client.js';
import { extractFromBitbucketUrl, getWorkspaceAndRepo } from '../utils/url-parser.js';

// Schema definitions
export const listPullRequestsSchema = z.object({
  workspace: z.string().optional().describe('Bitbucket workspace name (defaults to BITBUCKET_WORKSPACE env var or extracted from prUrl)'),
  repository: z.string().optional().describe('Repository slug/name (defaults to BITBUCKET_REPOSITORY env var or extracted from prUrl)'),
  prUrl: z.string().optional().describe('Pull request URL to extract workspace/repository from (e.g., https://bitbucket.org/workspace/repo/pull-requests/123)'),
  state: z.enum(['OPEN', 'MERGED', 'DECLINED', 'SUPERSEDED']).optional().describe('Filter by PR state'),
  author: z.string().optional().describe('Filter by author username'),
});

export const readPullRequestSchema = z.object({
  workspace: z.string().optional().describe('Bitbucket workspace name (defaults to BITBUCKET_WORKSPACE env var or extracted from prUrl)'),
  repository: z.string().optional().describe('Repository slug/name (defaults to BITBUCKET_REPOSITORY env var or extracted from prUrl)'),
  prUrl: z.string().optional().describe('Pull request URL to extract workspace/repository/PR ID from (e.g., https://bitbucket.org/workspace/repo/pull-requests/123)'),
  pullRequestId: z.number().optional().describe('Pull request ID (can be extracted from prUrl if provided)'),
  includeDiff: z.boolean().optional().describe('Include diff in response'),
  includeComments: z.boolean().optional().describe('Include comments in response'),
});

export const createPullRequestSchema = z.object({
  workspace: z.string().optional().describe('Bitbucket workspace name (defaults to BITBUCKET_WORKSPACE env var or extracted from prUrl)'),
  repository: z.string().optional().describe('Repository slug/name (defaults to BITBUCKET_REPOSITORY env var or extracted from prUrl)'),
  prUrl: z.string().optional().describe('Pull request URL to extract workspace/repository from (e.g., https://bitbucket.org/workspace/repo/pull-requests/123)'),
  title: z.string().describe('PR title'),
  description: z.string().optional().describe('PR description'),
  sourceBranch: z.string().describe('Source branch name'),
  destinationBranch: z.string().optional().describe('Destination branch (default: main)'),
  reviewers: z.array(z.string()).optional().describe('List of reviewer usernames'),
  closeSourceBranch: z.boolean().optional().describe('Close source branch after merge'),
  autoGenerateDescription: z.boolean().optional().describe('Auto-generate description from commits'),
});

export const updatePullRequestSchema = z.object({
  workspace: z.string().optional().describe('Bitbucket workspace name (defaults to BITBUCKET_WORKSPACE env var or extracted from prUrl)'),
  repository: z.string().optional().describe('Repository slug/name (defaults to BITBUCKET_REPOSITORY env var or extracted from prUrl)'),
  prUrl: z.string().optional().describe('Pull request URL to extract workspace/repository/PR ID from (e.g., https://bitbucket.org/workspace/repo/pull-requests/123)'),
  pullRequestId: z.number().optional().describe('Pull request ID (can be extracted from prUrl if provided)'),
  title: z.string().optional().describe('Update PR title'),
  description: z.string().optional().describe('Update PR description'),
  reviewers: z.array(z.string()).optional().describe('Update reviewers (replaces existing)'),
  state: z.enum(['OPEN', 'MERGED', 'DECLINED']).optional().describe('Update PR state'),
  mergeStrategy: z.enum(['merge_commit', 'squash', 'fast_forward']).optional().describe('Merge strategy (only when merging)'),
  comment: z.string().optional().describe('Add a comment to the PR'),
  commentFilePath: z.string().optional().describe('File path for line-specific comment (must match a file path from the diff)'),
  commentLineNumber: z.number().optional().describe('NEW file line number from the diff output (the number shown on + or context lines). Must be a line visible in the diff.'),
});

export const replyToCommentSchema = z.object({
  workspace: z.string().optional().describe('Bitbucket workspace name (defaults to BITBUCKET_WORKSPACE env var or extracted from prUrl)'),
  repository: z.string().optional().describe('Repository slug/name (defaults to BITBUCKET_REPOSITORY env var or extracted from prUrl)'),
  prUrl: z.string().optional().describe('Pull request URL to extract workspace/repository/PR ID from (e.g., https://bitbucket.org/workspace/repo/pull-requests/123)'),
  pullRequestId: z.number().optional().describe('Pull request ID (can be extracted from prUrl if provided)'),
  parentCommentId: z.number().describe('ID of the comment to reply to'),
  content: z.string().describe('Reply content'),
});

// Tool definitions
export const listPullRequestsTool = {
  name: 'list_pull_requests',
  description:
    'List pull requests by status (open, merged, declined), filter by repository, author, or Jira ticket',
  inputSchema: {
    type: 'object',
    properties: {
      workspace: {
        type: 'string',
        description: 'Bitbucket workspace name (defaults to BITBUCKET_WORKSPACE env var or extracted from prUrl)',
      },
      repository: {
        type: 'string',
        description: 'Repository slug/name (defaults to BITBUCKET_REPOSITORY env var or extracted from prUrl)',
      },
      prUrl: {
        type: 'string',
        description: 'Pull request URL to extract workspace/repository from (e.g., https://bitbucket.org/workspace/repo/pull-requests/123)',
      },
      state: {
        type: 'string',
        enum: ['OPEN', 'MERGED', 'DECLINED', 'SUPERSEDED'],
        description: 'Filter by PR state',
      },
      author: { type: 'string', description: 'Filter by author username' },
    },
    required: [],
  },
};

export const readPullRequestTool = {
  name: 'read_pull_request',
  description:
    'Get PR details including title, description, status, reviewers, diff, comments, and approvals. Extracts linked Jira tickets from PR description. Can extract workspace/repository/PR ID from a PR URL.',
  inputSchema: {
    type: 'object',
    properties: {
      workspace: {
        type: 'string',
        description: 'Bitbucket workspace name (defaults to BITBUCKET_WORKSPACE env var or extracted from prUrl)',
      },
      repository: {
        type: 'string',
        description: 'Repository slug/name (defaults to BITBUCKET_REPOSITORY env var or extracted from prUrl)',
      },
      prUrl: {
        type: 'string',
        description: 'Pull request URL to extract workspace/repository/PR ID from (e.g., https://bitbucket.org/workspace/repo/pull-requests/123)',
      },
      pullRequestId: { type: 'number', description: 'Pull request ID (can be extracted from prUrl if provided)' },
      includeDiff: { type: 'boolean', description: 'Include diff in response' },
      includeComments: { type: 'boolean', description: 'Include comments in response' },
    },
    required: [],
  },
};

export const createPullRequestTool = {
  name: 'create_pull_request',
  description:
    'Create PR with title, description, source/target branches. Auto-generate description from commits and auto-link to Jira ticket if mentioned. Can extract workspace/repository from a PR URL.',
  inputSchema: {
    type: 'object',
    properties: {
      workspace: {
        type: 'string',
        description: 'Bitbucket workspace name (defaults to BITBUCKET_WORKSPACE env var or extracted from prUrl)',
      },
      repository: {
        type: 'string',
        description: 'Repository slug/name (defaults to BITBUCKET_REPOSITORY env var or extracted from prUrl)',
      },
      prUrl: {
        type: 'string',
        description: 'Pull request URL to extract workspace/repository from (e.g., https://bitbucket.org/workspace/repo/pull-requests/123)',
      },
      title: { type: 'string', description: 'PR title' },
      description: { type: 'string', description: 'PR description' },
      sourceBranch: { type: 'string', description: 'Source branch name' },
      destinationBranch: { type: 'string', description: 'Destination branch (default: main)' },
      reviewers: {
        type: 'array',
        items: { type: 'string' },
        description: 'List of reviewer usernames',
      },
      closeSourceBranch: {
        type: 'boolean',
        description: 'Close source branch after merge',
      },
      autoGenerateDescription: {
        type: 'boolean',
        description: 'Auto-generate description from commits',
      },
    },
    required: ['title', 'sourceBranch'],
  },
};

export const updatePullRequestTool = {
  name: 'update_pull_request',
  description:
    'Update PR title, description, or status. Add/remove reviewers, add comments (general or inline line-specific), or merge PR with merge strategy option. For inline comments on specific lines, provide comment, commentFilePath, and commentLineNumber together. Can extract workspace/repository/PR ID from a PR URL.',
  inputSchema: {
    type: 'object',
    properties: {
      workspace: {
        type: 'string',
        description: 'Bitbucket workspace name (defaults to BITBUCKET_WORKSPACE env var or extracted from prUrl)',
      },
      repository: {
        type: 'string',
        description: 'Repository slug/name (defaults to BITBUCKET_REPOSITORY env var or extracted from prUrl)',
      },
      prUrl: {
        type: 'string',
        description: 'Pull request URL to extract workspace/repository/PR ID from (e.g., https://bitbucket.org/workspace/repo/pull-requests/123)',
      },
      pullRequestId: { type: 'number', description: 'Pull request ID (can be extracted from prUrl if provided)' },
      title: { type: 'string', description: 'Update PR title' },
      description: { type: 'string', description: 'Update PR description' },
      reviewers: {
        type: 'array',
        items: { type: 'string' },
        description: 'Update reviewers (replaces existing)',
      },
      state: {
        type: 'string',
        enum: ['OPEN', 'MERGED', 'DECLINED'],
        description: 'Update PR state',
      },
      mergeStrategy: {
        type: 'string',
        enum: ['merge_commit', 'squash', 'fast_forward'],
        description: 'Merge strategy (only when merging)',
      },
      comment: {
        type: 'string',
        description:
          'Add a comment to the PR. To create an inline comment on a specific line, also provide commentFilePath and commentLineNumber.',
      },
      commentFilePath: {
        type: 'string',
        description:
          'File path for inline comment (must match a file path from the diff, e.g., "src/models/trex/BiFastDetail.ts"). Required for line-specific comments. Must be provided together with commentLineNumber.',
      },
      commentLineNumber: {
        type: 'number',
        description:
          'NEW file line number from the diff output for inline comment. Use the line number shown on + (added) or context lines in the diff. The line MUST be visible in the diff. Must be provided together with commentFilePath.',
      },
    },
    required: [],
  },
};

export const replyToCommentTool = {
  name: 'reply_to_comment',
  description:
    'Reply to an existing comment on a pull request. Creates a threaded reply to a specific comment by its ID.',
  inputSchema: {
    type: 'object',
    properties: {
      workspace: {
        type: 'string',
        description: 'Bitbucket workspace name (defaults to BITBUCKET_WORKSPACE env var or extracted from prUrl)',
      },
      repository: {
        type: 'string',
        description: 'Repository slug/name (defaults to BITBUCKET_REPOSITORY env var or extracted from prUrl)',
      },
      prUrl: {
        type: 'string',
        description: 'Pull request URL to extract workspace/repository/PR ID from (e.g., https://bitbucket.org/workspace/repo/pull-requests/123)',
      },
      pullRequestId: { type: 'number', description: 'Pull request ID (can be extracted from prUrl if provided)' },
      parentCommentId: { type: 'number', description: 'ID of the comment to reply to' },
      content: { type: 'string', description: 'Reply content' },
    },
    required: ['parentCommentId', 'content'],
  },
};

// Helper functions
function extractJiraTickets(text: string): string[] {
  const jiraPattern = /\b([A-Z]+-\d+)\b/g;
  const matches = text.match(jiraPattern);
  return matches ? [...new Set(matches)] : [];
}

// Handler functions
export async function handleListPullRequests(
  client: BitbucketClient,
  args: unknown,
): Promise<{ content: { type: 'text'; text: string }[] }> {
  const parsed = listPullRequestsSchema.parse(args);
  const { workspace, repository } = getWorkspaceAndRepo(parsed);
  const { state, author } = parsed;

  const prs = await client.listPullRequests(workspace, repository, state);

  // Filter by author if provided
  let filteredPRs = prs.values;
  if (author) {
    filteredPRs = filteredPRs.filter(
      (pr) => pr.author?.username?.toLowerCase() === author.toLowerCase(),
    );
  }

  const text = [
    `# Pull Requests: ${workspace}/${repository}`,
    '',
    state ? `**State Filter:** ${state}` : '',
    author ? `**Author Filter:** ${author}` : '',
    '',
    `**Found ${filteredPRs.length} pull request(s)**`,
    '',
    ...filteredPRs.map((pr) => {
      const jiraTickets = pr.description ? extractJiraTickets(pr.description) : [];
      return [
        `## PR #${pr.id}: ${pr.title}`,
        '',
        `**State:** ${pr.state}`,
        pr.source?.branch ? `**Source:** ${pr.source.branch.name}` : '',
        pr.destination?.branch ? `**Destination:** ${pr.destination.branch.name}` : '',
        pr.author?.displayName ? `**Author:** ${pr.author.displayName} (@${pr.author.username || ''})` : '',
        pr.createdOn ? `**Created:** ${new Date(pr.createdOn).toLocaleString()}` : '',
        pr.updatedOn ? `**Updated:** ${new Date(pr.updatedOn).toLocaleString()}` : '',
        pr.reviewers && pr.reviewers.length > 0
          ? `**Reviewers:** ${pr.reviewers.map((r) => r.displayName || r.username).join(', ')}`
          : '',
        jiraTickets.length > 0 ? `**Jira Tickets:** ${jiraTickets.join(', ')}` : '',
        pr.description ? `\n**Description:**\n${pr.description.substring(0, 200)}${pr.description.length > 200 ? '...' : ''}` : '',
      ]
        .filter(Boolean)
        .join('\n');
    }),
  ]
    .filter(Boolean)
    .join('\n\n');

  return {
    content: [{ type: 'text', text }],
  };
}

export async function handleReadPullRequest(
  client: BitbucketClient,
  args: unknown,
): Promise<{ content: { type: 'text'; text: string }[] }> {
  const parsed = readPullRequestSchema.parse(args);
  const { workspace, repository } = getWorkspaceAndRepo(parsed);

  // Extract PR ID from URL if provided
  let pullRequestId = parsed.pullRequestId;
  if (!pullRequestId && parsed.prUrl) {
    const extracted = extractFromBitbucketUrl(parsed.prUrl);
    if (extracted?.prId) {
      pullRequestId = extracted.prId;
    }
  }

  if (!pullRequestId) {
    throw new Error('Pull request ID is required. Provide it directly or in a PR URL.');
  }

  const { includeDiff, includeComments } = parsed;

  const pr = await client.getPullRequest(workspace, repository, pullRequestId);
  const jiraTickets = pr.description ? extractJiraTickets(pr.description) : [];

  let text = [
    `# Pull Request #${pr.id}: ${pr.title}`,
    '',
    `**State:** ${pr.state}`,
    pr.source?.branch ? `**Source Branch:** ${pr.source.branch.name}` : '',
    pr.destination?.branch ? `**Destination Branch:** ${pr.destination.branch.name}` : '',
    pr.source?.commit ? `**Source Commit:** \`${pr.source.commit.hash.substring(0, 7)}\`` : '',
    pr.author?.displayName
      ? `**Author:** ${pr.author.displayName} (@${pr.author.username || ''})`
      : '',
    pr.createdOn ? `**Created:** ${new Date(pr.createdOn).toLocaleString()}` : '',
    pr.updatedOn ? `**Updated:** ${new Date(pr.updatedOn).toLocaleString()}` : '',
    pr.reviewers && pr.reviewers.length > 0
      ? `**Reviewers:** ${pr.reviewers
        .map((r) => {
          const name = r.displayName || r.username || 'Unknown';
          const approved = r.approved ? ' ✓ Approved' : '';
          return `${name}${approved}`;
        })
        .join(', ')}`
      : '',
    jiraTickets.length > 0 ? `**Jira Tickets:** ${jiraTickets.join(', ')}` : '',
    pr.description ? `\n## Description\n\n${pr.description}` : '',
  ]
    .filter(Boolean)
    .join('\n');

  if (includeDiff) {
    try {
      const diff = await client.getPullRequestDiff(workspace, repository, pullRequestId);
      text += '\n\n## Diff\n\n';
      text += `**Files Changed:** ${diff.files.length}\n`;
      text += `**Additions:** +${diff.stats?.additions || 0}\n`;
      text += `**Deletions:** -${diff.stats?.deletions || 0}\n\n`;
      text += '### Changed Files:\n';
      text += diff.files
        .map((f) => {
          const status = f.status === 'added' ? '+' : f.status === 'removed' ? '-' : 'M';
          return `- ${status} ${f.path}${f.oldPath && f.oldPath !== f.path ? ` (from ${f.oldPath})` : ''} (+${f.additions || 0}/-${f.deletions || 0})`;
        })
        .join('\n');

      // Render full diff with line numbers for inline comment targeting
      text += '\n\n### Diff Content\n';
      text += '> IMPORTANT: When posting inline comments, use the NEW line number shown below (the number after the | on + and context lines). Only lines visible in this diff can receive inline comments.\n\n';
      for (const f of diff.files) {
        if (!f.hunks || f.hunks.length === 0) continue;
        text += `\n#### ${f.path}\n`;
        text += '```diff\n';
        for (const hunk of f.hunks) {
          text += `${hunk.header}\n`;
          for (const line of hunk.lines) {
            if (line.type === 'add') {
              text += `+  ${String(line.newLine).padStart(4)} | ${line.content}\n`;
            } else if (line.type === 'remove') {
              text += `-  ${String(line.oldLine).padStart(4)} | ${line.content}\n`;
            } else {
              text += `   ${String(line.newLine).padStart(4)} | ${line.content}\n`;
            }
          }
        }
        text += '```\n';
      }
    } catch (error: any) {
      text += `\n\n**Note:** Could not fetch diff: ${error.message}`;
    }
  }

  if (includeComments) {
    try {
      const comments = await client.getPullRequestComments(workspace, repository, pullRequestId);
      if (comments.length > 0) {
        text += '\n\n## Comments\n\n';
        text += comments
          .map((c) => {
            const author = c.author?.displayName || c.author?.username || 'Unknown';
            const date = c.createdOn ? new Date(c.createdOn).toLocaleString() : '';
            const content = c.content?.raw || c.content?.markup || '(no content)';
            const commentId = `**Comment ID:** ${c.id}`;
            const parentInfo = c.parent?.id ? `**Reply to Comment:** #${c.parent.id}` : '';
            const inlineInfo = c.inline?.path ? `**File:** ${c.inline.path} (Line ${c.inline.to})` : '';
            return [
              `### ${author} (${date})`,
              commentId,
              parentInfo,
              inlineInfo,
              '',
              content,
            ].filter(Boolean).join('\n');
          })
          .join('\n\n---\n\n');
      }
    } catch (error: any) {
      text += `\n\n**Note:** Could not fetch comments: ${error.message}`;
    }
  }

  return {
    content: [{ type: 'text', text }],
  };
}

export async function handleCreatePullRequest(
  client: BitbucketClient,
  args: unknown,
): Promise<{ content: { type: 'text'; text: string }[] }> {
  const parsed = createPullRequestSchema.parse(args);
  const { workspace, repository } = getWorkspaceAndRepo(parsed);
  const {
    title,
    description,
    sourceBranch,
    destinationBranch,
    reviewers,
    closeSourceBranch,
    autoGenerateDescription,
  } = parsed;

  let finalDescription = description || '';

  // Auto-generate description from commits if requested
  if (autoGenerateDescription && !description) {
    try {
      const commits = await client.listCommits(workspace, repository, sourceBranch, 1, 10);
      if (commits.values.length > 0) {
        finalDescription = '## Changes\n\n';
        finalDescription += commits.values
          .map((c) => {
            const hash = c.hash.substring(0, 7);
            const message = (c.message || '').split('\n')[0];
            return `- \`${hash}\` ${message}`;
          })
          .join('\n');
      }
    } catch (error: any) {
      // If we can't get commits, just continue without auto-generation
    }
  }

  const pr = await client.createPullRequest({
    workspace,
    repository,
    title,
    description: finalDescription,
    sourceBranch,
    destinationBranch,
    reviewers,
    closeSourceBranch,
  });

  const jiraTickets = finalDescription ? extractJiraTickets(finalDescription) : [];

  const text = [
    `# Pull Request Created: #${pr.id}`,
    '',
    `**Title:** ${pr.title}`,
    `**State:** ${pr.state}`,
    pr.source?.branch ? `**Source Branch:** ${pr.source.branch.name}` : '',
    pr.destination?.branch ? `**Destination Branch:** ${pr.destination.branch.name}` : '',
    pr.author?.displayName
      ? `**Author:** ${pr.author.displayName} (@${pr.author.username || ''})`
      : '',
    pr.reviewers && pr.reviewers.length > 0
      ? `**Reviewers:** ${pr.reviewers.map((r) => r.displayName || r.username).join(', ')}`
      : '',
    jiraTickets.length > 0 ? `**Jira Tickets Found:** ${jiraTickets.join(', ')}` : '',
    finalDescription ? `\n## Description\n\n${finalDescription}` : '',
  ]
    .filter(Boolean)
    .join('\n');

  return {
    content: [{ type: 'text', text }],
  };
}

export async function handleUpdatePullRequest(
  client: BitbucketClient,
  args: unknown,
): Promise<{ content: { type: 'text'; text: string }[] }> {
  const parsed = updatePullRequestSchema.parse(args);
  const { workspace, repository } = getWorkspaceAndRepo(parsed);

  // Extract PR ID from URL if provided
  let pullRequestId = parsed.pullRequestId;
  if (!pullRequestId && parsed.prUrl) {
    const extracted = extractFromBitbucketUrl(parsed.prUrl);
    if (extracted?.prId) {
      pullRequestId = extracted.prId;
    }
  }

  if (!pullRequestId) {
    throw new Error('Pull request ID is required. Provide it directly or in a PR URL.');
  }

  const {
    title,
    description,
    reviewers,
    state,
    mergeStrategy,
    comment,
    commentFilePath,
    commentLineNumber,
  } = parsed;

  // If merging, use merge endpoint
  if (state === 'MERGED') {
    const pr = await client.mergePullRequest(
      workspace,
      repository,
      pullRequestId,
      mergeStrategy || 'merge_commit',
    );
    return {
      content: [
        {
          type: 'text',
          text: `# Pull Request #${pr.id} Merged\n\n**State:** ${pr.state}\n**Merge Strategy:** ${mergeStrategy || 'merge_commit'}`,
        },
      ],
    };
  }

  // Otherwise, update the PR
  const updateParams: any = {
    workspace,
    repository,
    pullRequestId,
  };

  if (title) updateParams.title = title;
  if (description !== undefined) updateParams.description = description;
  if (reviewers) updateParams.reviewers = reviewers;
  if (state) updateParams.state = state;

  const pr = await client.updatePullRequest(updateParams);

  // Add comment if provided
  if (comment) {
    try {
      console.error(
        `Adding comment with filePath: ${commentFilePath}, lineNumber: ${commentLineNumber}`,
      );
      const commentResult = await client.addPullRequestComment(
        workspace,
        repository,
        pullRequestId,
        comment,
        commentFilePath,
        commentLineNumber,
      );
      // Log success for debugging
      console.error(
        `Comment added successfully: ID ${commentResult.id}, inline: ${JSON.stringify(commentResult.inline)}`,
      );
    } catch (error: any) {
      // Log error instead of silently failing
      console.error(`Failed to add comment: ${error.message}`);
      throw new Error(`Failed to add comment to PR: ${error.message}`);
    }
  }

  const commentInfo = comment
    ? commentFilePath && commentLineNumber !== undefined
      ? `\n**Line Comment Added:** ${comment}\n**File:** ${commentFilePath}\n**Line:** ${commentLineNumber}`
      : `\n**Comment Added:** ${comment}`
    : '';

  const text = [
    `# Pull Request #${pr.id} Updated`,
    '',
    `**Title:** ${pr.title}`,
    `**State:** ${pr.state}`,
    pr.source?.branch ? `**Source Branch:** ${pr.source.branch.name}` : '',
    pr.destination?.branch ? `**Destination Branch:** ${pr.destination.branch.name}` : '',
    pr.reviewers && pr.reviewers.length > 0
      ? `**Reviewers:** ${pr.reviewers.map((r) => r.displayName || r.username).join(', ')}`
      : '',
    commentInfo,
  ]
    .filter(Boolean)
    .join('\n');

  return {
    content: [{ type: 'text', text }],
  };
}


export async function handleReplyToComment(
  client: BitbucketClient,
  args: unknown,
): Promise<{ content: { type: 'text'; text: string }[] }> {
  const parsed = replyToCommentSchema.parse(args);
  const { workspace, repository } = getWorkspaceAndRepo(parsed);

  // Extract PR ID from URL if provided
  let pullRequestId = parsed.pullRequestId;
  if (!pullRequestId && parsed.prUrl) {
    const extracted = extractFromBitbucketUrl(parsed.prUrl);
    if (extracted?.prId) {
      pullRequestId = extracted.prId;
    }
  }

  if (!pullRequestId) {
    throw new Error('Pull request ID is required. Provide it directly or in a PR URL.');
  }

  const { parentCommentId, content } = parsed;

  const reply = await client.replyToPullRequestComment(
    workspace,
    repository,
    pullRequestId,
    parentCommentId,
    content,
  );

  const text = [
    `# Reply Added to Comment #${parentCommentId}`,
    '',
    `**Reply ID:** ${reply.id}`,
    `**Author:** ${reply.author?.displayName || reply.author?.username || 'Unknown'}`,
    reply.createdOn ? `**Created:** ${new Date(reply.createdOn).toLocaleString()}` : '',
    reply.parent?.id ? `**In Reply To:** Comment #${reply.parent.id}` : '',
    '',
    `**Content:**`,
    content,
  ]
    .filter(Boolean)
    .join('\n');

  return {
    content: [{ type: 'text', text }],
  };
}
